### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ichala** [ichala/Ruby-Capstone#36]
- Github Project Link : [Here](https://github.com/users/ichala/projects/2)
- We Have 3 Team Members: @mandelatuks @kwambiee and me (@ichala )

1. Team 1 : @ichala 
2. Team 2 : @mandelatuks 
3. Team 3 : @kwambiee

**Comment by addod19** [comment]
### Hi @ichala , @mandelatuks and @kwambiee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [x] Points are evenly distributed among group members :+1: 
- [x] All cards assigned to members :100: 
- [x] Board has all the required columns :1st_place_medal: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
